name: xauusd-scalping
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip>=23.0
  
  # CUDA Support
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - cudatoolkit=11.8
  - cupy=12.2.0
  
  # Core Scientific Computing
  - numpy=1.24.3
  - pandas=2.0.3
  - scipy=1.11.1
  - scikit-learn=1.3.0
  - numba=0.58.0
  
  # Data Storage & Processing
  - polars=0.18.8
  - pyarrow=13.0.0
  - h5py=3.9.0
  - lz4=4.3.2
  
  # System Tools
  - git
  - gcc_linux-64  # Linux
  - gxx_linux-64  # Linux
  
  # Pip packages
  - pip:
    - lightgbm==4.0.0
    - xgboost==2.0.0
    - transformers==4.33.0
    - optuna==3.3.0
    - ta-lib==0.4.25
    - mplfinance==0.12.9b0
    - vectorbt==0.25.4
    - yfinance==0.2.18
    - ccxt==4.0.77
    - websocket-client==1.6.1
    - aiohttp==3.8.5
    - asyncio-throttle==1.0.2
    - matplotlib==3.7.2
    - seaborn==0.12.2
    - plotly==5.15.0
    - shap==0.42.1
    - lime==0.2.0.1
    - structlog==23.1.0
    - click==8.1.6
    - pydantic==2.3.0
    - fastapi==0.103.0
    - uvicorn==0.23.2
    - redis==4.6.0
    - psutil==5.9.5
    - pytest==7.4.0
    - pytest-cov==4.1.0
    - pytest-asyncio==0.21.1
    - black==23.7.0
    - flake8==6.0.0
    - mypy==1.5.1
    - pre-commit==3.3.3
    - uvloop==0.17.0
    - aiofiles==23.2.1
    - asyncpg==0.28.0
    - motor==3.3.1
    - prometheus-client==0.17.1
    - grafana-api==1.0.3